parameters:
    #

doctrine:
    dbal:
        # configure these for your database server
        driver: '%env(DB_DRIVER)%'
        # server_version: '5.7'
        server_version: 'mariadb-10.3.16'
        charset: utf8mb4
        url: 'mysql://%env(DB_USER)%:%env(DB_PASSWORD)%@%env(DB_HOST)%:3306/%env(DB_NAME)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
