#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
logout:
    path: /logout

admin_area:
    resource: ../src/Controller/AdminArea/
    type:     annotation
    prefix:   /a
